name: Deploy to Railway

on:
  push:
    branches:
      - MergeCalidad

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          service: "ea4ecc15-a7bf-4684-b666-cc77bdb573cc"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
